{{- if and (not .Values.existingSecret) (or (index .Values.env "ANKIWEB_USERNAME") (index .Values.env "ANKIWEB_PASSWORD") (index .Values.env "ANKI_BACKUP_API_TOKEN")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anki-backup-tool.fullname" . }}-credentials
  labels:
    {{- include "anki-backup-tool.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
